# RazorShield AI - RBI & PCI-DSS Compliant Forensic Evidence Dossier Generator
import time
import hashlib
import json
from typing import Dict, Any
from app.models import InvestigationReport

class DossierGenerator:
    @staticmethod
    def generate_rbi_json(report: InvestigationReport) -> Dict[str, Any]:
        """
        Synthesizes structured dossier adhering to:
        - RBI Master Directions on Cyber Security in Payment Systems
        - RBI DPSS Real-Time Fraud Reporting Framework
        - PCI-DSS v4.0 Requirement 10.2 Audit Integrity
        """
        payload_to_hash = f"{report.case_id}|{report.target_entity}|{report.generated_at}|{report.recommended_firewall_rule.condition_dsl}"
        crypto_hash = hashlib.sha256(payload_to_hash.encode('utf-8')).hexdigest()

        return {
            "compliance_standard": "RBI/2023-24/Master-Directions-Cyber-Security",
            "regulatory_framework": "Reserve Bank of India - Department of Payment and Settlement Systems (DPSS)",
            "classification": "STRICTLY CONFIDENTIAL // FINTECH FORENSIC EVIDENCE",
            "audit_sha256_seal": crypto_hash,
            "case_metadata": {
                "case_id": report.case_id,
                "investigation_timestamp": report.generated_at,
                "target_entity": report.target_entity,
                "confidence_score": f"{report.confidence_score}%",
                "risk_status": "CONFIRMED_SYNDICATE_FRAUD" if report.confidence_score >= 80 else "SUSPICIOUS_ANOMALY"
            },
            "executive_summary": report.summary,
            "financial_impact": {
                "prevented_fraud_loss_inr": report.blast_radius.fraud_volume_prevented_inr,
                "affected_syndicate_nodes": report.blast_radius.affected_entities_count,
                "estimated_false_positive_pct": f"{report.blast_radius.false_positive_rate_pct:.3f}%"
            },
            "syndicate_members": report.syndicate_members,
            "chronological_evidence_trail": [item.dict() for item in report.evidence_trail],
            "enforced_firewall_remediation": {
                "rule_id": report.recommended_firewall_rule.rule_id,
                "rule_name": report.recommended_firewall_rule.name,
                "action": report.recommended_firewall_rule.action,
                "condition_dsl": report.recommended_firewall_rule.condition_dsl,
                "deployment_status": report.recommended_firewall_rule.status
            },
            "statutory_declarations": [
                "This document constitutes automated digital evidence generated by RazorShield AI Tier-2 Autonomous Copilot.",
                "All cryptographic signatures and sliding-window velocity logs are immutably recorded for regulatory submission under Section 65B of the Indian Evidence Act."
            ]
        }

    @staticmethod
    def generate_html_dossier(report: InvestigationReport) -> str:
        """
        Generates clean, printable HTML document with FinTech security styling.
        """
        rbi_data = DossierGenerator.generate_rbi_json(report)
        crypto_hash = rbi_data["audit_sha256_seal"]

        members_html = "".join([
            f"""<tr>
                <td style="padding: 8px; border-bottom: 1px solid #2d3748; font-family: monospace; color: #63b3ed;">{m.get('id')}</td>
                <td style="padding: 8px; border-bottom: 1px solid #2d3748; text-transform: uppercase; font-size: 11px;">{m.get('type')}</td>
                <td style="padding: 8px; border-bottom: 1px solid #2d3748;">{m.get('role')}</td>
                <td style="padding: 8px; border-bottom: 1px solid #2d3748; color: {'#fc8181' if m.get('risk_level') == 'critical' else '#f6e05e'};">{m.get('risk_level')}</td>
            </tr>""" for m in report.syndicate_members
        ])

        evidence_html = "".join([
            f"""<div style="margin-bottom: 12px; padding-left: 14px; border-left: 3px solid #4299e1;">
                <div style="font-size: 11px; color: #a0aec0;">[{ev.timestamp}] - <strong>{ev.source}</strong> ({ev.severity})</div>
                <div style="font-size: 13px; color: #e2e8f0; margin-top: 2px;">{ev.detail}</div>
            </div>""" for ev in report.evidence_trail
        ])

        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>RazorShield AI - RBI Forensic Dossier [{report.case_id}]</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #f8fafc; padding: 40px; line-height: 1.5; }}
        .card {{ background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 24px; margin-bottom: 24px; }}
        .header {{ display: flex; justify-content: space-between; border-bottom: 2px solid #3b82f6; padding-bottom: 16px; margin-bottom: 24px; }}
        .badge {{ background: #991b1b; color: #fecaca; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: bold; }}
        .stat-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 16px 0; }}
        .stat-box {{ background: #0f172a; padding: 12px; border-radius: 6px; border: 1px solid #334155; }}
        table {{ width: 100%; border-collapse: collapse; text-align: left; font-size: 13px; }}
        th {{ background: #0f172a; padding: 8px; color: #94a3b8; font-weight: 600; }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1 style="margin: 0; font-size: 22px; color: #60a5fa;">RAZORSHIELD AI // REGULATORY FORENSIC DOSSIER</h1>
            <div style="font-size: 12px; color: #94a3b8; margin-top: 4px;">COMPLIANCE: RBI Master Directions on Cyber Security | DPSS Risk Framework</div>
        </div>
        <div style="text-align: right;">
            <span class="badge">STRICTLY CONFIDENTIAL</span>
            <div style="font-size: 11px; color: #94a3b8; margin-top: 6px;">CASE REF: {report.case_id}</div>
        </div>
    </div>

    <div class="card">
        <h2 style="font-size: 16px; margin-top: 0; color: #38bdf8;">1. Executive Summary & Impact Analysis</h2>
        <p style="color: #cbd5e1; font-size: 14px;">{report.summary}</p>
        
        <div class="stat-grid">
            <div class="stat-box">
                <div style="font-size: 11px; color: #94a3b8;">FRAUD VOLUME MITIGATED</div>
                <div style="font-size: 18px; font-weight: bold; color: #4ade80;">₹{report.blast_radius.fraud_volume_prevented_inr:,.2f}</div>
            </div>
            <div class="stat-box">
                <div style="font-size: 11px; color: #94a3b8;">CONFIDENCE SCORE</div>
                <div style="font-size: 18px; font-weight: bold; color: #60a5fa;">{report.confidence_score}%</div>
            </div>
            <div class="stat-box">
                <div style="font-size: 11px; color: #94a3b8;">FALSE POSITIVE RATIO</div>
                <div style="font-size: 18px; font-weight: bold; color: #fbbf24;">{report.blast_radius.false_positive_rate_pct:.3f}%</div>
            </div>
        </div>
    </div>

    <div class="card">
        <h2 style="font-size: 16px; margin-top: 0; color: #38bdf8;">2. Syndicate Topology & Entity Mapping</h2>
        <table>
            <thead>
                <tr>
                    <th>Entity Identifier</th>
                    <th>Type</th>
                    <th>Forensic Attribution Role</th>
                    <th>Risk State</th>
                </tr>
            </thead>
            <tbody>
                {members_html}
            </tbody>
        </table>
    </div>

    <div class="card">
        <h2 style="font-size: 16px; margin-top: 0; color: #38bdf8;">3. Chronological Audit Evidence Trail</h2>
        {evidence_html}
    </div>

    <div class="card">
        <h2 style="font-size: 16px; margin-top: 0; color: #38bdf8;">4. Autonomous Adaptive Firewall Remediation</h2>
        <div style="background: #0f172a; padding: 12px; border-radius: 6px; font-family: monospace; font-size: 13px; color: #f43f5e;">
            <strong>RULE ID:</strong> {report.recommended_firewall_rule.rule_id}<br/>
            <strong>ACTION:</strong> {report.recommended_firewall_rule.action} | <strong>STATUS:</strong> {report.recommended_firewall_rule.status}<br/>
            <strong>CONDITION DSL:</strong> {report.recommended_firewall_rule.condition_dsl}
        </div>
    </div>

    <div style="font-size: 11px; color: #64748b; border-top: 1px solid #334155; padding-top: 16px; display: flex; justify-content: space-between;">
        <div>DIGITAL EVIDENCE SEAL: <span style="font-family: monospace; color: #94a3b8;">SHA256:{crypto_hash}</span></div>
        <div>GENERATED BY: RazorShield AI Autonomous Copilot</div>
    </div>
</body>
</html>"""
